spring:
  application:
    name: pet
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # Optional: Use a specific naming strategy
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: ${DATABASE_DEFAULT_SCHEMA}
        show_sql: true
  #        connection:
  #          charSet: UTF-8
  #          useUnicode: true
  jackson:
    time-zone: UTC
  data:
    rest:
      default-page-size:
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui
server:
  port: 8080
